spring:
  datasource:
    url: jdbc:h2:mem:appdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true

    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2/console
server:
  port: 3000